// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Url struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiredAt sql.NullTime
	Dest      string
}
