// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: urls.sql

package database

import (
	"context"
	"database/sql"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (id, created_at, updated_at, expired_at, dest)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3
)
RETURNING id, created_at, updated_at, expired_at, dest
`

type CreateURLParams struct {
	ID        string
	ExpiredAt sql.NullTime
	Dest      string
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL, arg.ID, arg.ExpiredAt, arg.Dest)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiredAt,
		&i.Dest,
	)
	return i, err
}
